service: hello-service

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*"

functions:
  createItem:
    handler: handler.createItem
    events:
      - http:
          path: item
          method: post

  getItem:
    handler: handler.getItem
    events:
      - http:
          path: item/{id}
          method: get

resources:
  Resources:
    MyDynamoDBTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: "MyTable"
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST
