service: hello-service  # Mantener el nombre del servicio

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*"

functions:
  app:  # Cambia el nombre de la función principal a "app" para reflejar que usamos Express
    handler: handler.handler
    events:
      - http:
          path: item
          method: post
      - http:
          path: item/{id}
          method: get

resources:
  Resources:
    MyDynamoDBTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: "MyTable"
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST
